/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perencanalatihangym;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author lenovo
 */
public class WindowPull extends javax.swing.JFrame {

    /**
     * Creates new form outputWindow
     */
    public WindowPull() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Page Pull Day");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setText("Tentukan Latihan Pull Day (Back dan Bicep)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 19, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 301, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBox1.setText("Pull Up");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 84, 87, -1));

        jCheckBox2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBox2.setText("Lat Pull Down");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 84, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBox3.setText("Cable Row");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 120, 87, -1));

        jCheckBox4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBox4.setText("Face Pulls");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 120, 87, -1));

        jCheckBox5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBox5.setText("Single Arm Row");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 153, -1, 26));

        jCheckBox6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBox6.setText("Deadlift");
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 156, 87, -1));

        jCheckBox7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBox7.setText("Bicep Curl");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 195, 87, -1));

        jCheckBox8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBox8.setText("Bicep Curl Neutral Grip");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 195, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 51, 153));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Mulai Latihan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 301, -1, -1));

        jCheckBox9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBox9.setText("Dumbell/Barbell");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 262, -1, -1));

        jCheckBox10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBox10.setText("Machine/Cable");
        jPanel1.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 262, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Fasilitas Gym yang Digunakan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 234, -1, -1));

        jTextField1.setMinimumSize(new java.awt.Dimension(40, 26));
        jTextField1.setPreferredSize(new java.awt.Dimension(40, 26));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 81, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 83, 40, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 119, 40, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 119, 40, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 155, 40, -1));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 155, 47, -1));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 194, 40, -1));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 194, 47, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("*isi text field dengan repetisi (misal: 12x3)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 47, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perencanalatihangym/bg_pull.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -4, 560, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
        FormUtama frm = new FormUtama();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        latihanpullyangdipilih = "Latihan Pull Day yang Anda Dipilih: \n";
        arrLatihanPull = new JCheckBox[] {jCheckBox1, jCheckBox2, jCheckBox3,jCheckBox4,
                                          jCheckBox5, jCheckBox6, jCheckBox7, jCheckBox8};
        
        for (int i=0; i<arrLatihanPull.length; i++) {
            if(arrLatihanPull[i].isSelected())
                latihanpullyangdipilih += arrLatihanPull[i].getText() + "\n";
        }
        
        fasilitasgym = "Fasilitas/Alat Gym yang Digunakan: \n";
        arrFasilitasGymCheckBox = new JCheckBox[] {jCheckBox9, jCheckBox10};
        
        for (int i=0; i<arrFasilitasGymCheckBox.length; i++) {
            if(arrFasilitasGymCheckBox[i].isSelected())
                fasilitasgym += arrFasilitasGymCheckBox[i].getText() + "\n";
        }
        
        arrRepetisi = new JTextField[] {jTextField1, jTextField2, jTextField3, jTextField4,
                                        jTextField5, jTextField6, jTextField7, jTextField8};
        
        StringBuilder repetisiMessage = new StringBuilder("Jumlah Repetisi Dan Set yang Anda Mau:\n");
        for (JTextField textField : arrRepetisi) {
            String value = textField.getText();
            if (!value.isEmpty()) {
                repetisilatihan += value + "\n";
                repetisiMessage.append(value).append("\n");        
            
               }   
            }        

        if ((jTextField1.getText().isEmpty() && jCheckBox1.isSelected()) || 
            (jTextField2.getText().isEmpty() && jCheckBox2.isSelected()) ||
            (jTextField3.getText().isEmpty() && jCheckBox3.isSelected()) ||
            (jTextField4.getText().isEmpty() && jCheckBox4.isSelected()) || 
            (jTextField5.getText().isEmpty() && jCheckBox5.isSelected()) ||
            (jTextField6.getText().isEmpty() && jCheckBox6.isSelected()) ||
            (jTextField7.getText().isEmpty() && jCheckBox7.isSelected()) || 
            (jTextField8.getText().isEmpty() && jCheckBox8.isSelected()) )
        {
            JOptionPane.showMessageDialog(null, "Repetisi dan set belum ditentukan, Harap input dengan format RepetisixSet terlebih dahulu");
        }
        else if ((!jTextField1.getText().isEmpty() && !jCheckBox1.isSelected()) || 
            (!jTextField2.getText().isEmpty() && !jCheckBox2.isSelected()) ||
            (!jTextField3.getText().isEmpty() && !jCheckBox3.isSelected()) ||
            (!jTextField4.getText().isEmpty() && !jCheckBox4.isSelected()) || 
            (!jTextField5.getText().isEmpty() && !jCheckBox5.isSelected()) ||
            (!jTextField6.getText().isEmpty() && !jCheckBox6.isSelected()) ||
            (!jTextField7.getText().isEmpty() && !jCheckBox7.isSelected()) || 
            (!jTextField8.getText().isEmpty() && !jCheckBox8.isSelected()) )
        {
            JOptionPane.showMessageDialog(null, "Latihan Belum Terpilih, Harap Tentukan Pilihan Latihan yang Anda Inginkan");            
        }

        else if ((jTextField1.getText().isEmpty() && !jCheckBox1.isSelected()) && 
            (jTextField2.getText().isEmpty() && !jCheckBox2.isSelected()) &&
            (jTextField3.getText().isEmpty() && !jCheckBox3.isSelected()) &&
            (jTextField4.getText().isEmpty() && !jCheckBox4.isSelected()) && 
            (jTextField5.getText().isEmpty() && !jCheckBox5.isSelected()) &&
            (jTextField6.getText().isEmpty() && !jCheckBox6.isSelected()) &&
            (jTextField7.getText().isEmpty() && !jCheckBox7.isSelected()) && 
            (jTextField8.getText().isEmpty() && !jCheckBox8.isSelected()) )
        {
            JOptionPane.showMessageDialog(null, "Check Box dan Text Field Kosong, Harap Isi dengan Benar");            
 
        }
        else
        {   
            
            if (!jCheckBox9.isSelected() && !jCheckBox10.isSelected())
            {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Fasilitas/Alat yang Akan Digunakan");                            
            }
            
            else 
            {
            JOptionPane.showMessageDialog(this, latihanpullyangdipilih + "\n" + repetisiMessage.toString() +
            "\n"+ fasilitasgym,"Hasil Pilihan Latihan Anda", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowPull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowPull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowPull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowPull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowPull().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
    
    String latihanpullyangdipilih = "";
    JCheckBox[] arrLatihanPull;
    String fasilitasgym = "";
    JCheckBox[] arrFasilitasGymCheckBox;
    String repetisilatihan ="";
    JTextField[] arrRepetisi;
}
